package org.simulationsystems.simulationframework.simulation.adapters.api;

import java.util.UUID;

/*
 * A Simulation Run Group can consist of multiple simulation runs.  The Simulation Run Group is identified by the simulation developer using the Common Simulation Framework.  The ID should be globally unique and specified in the configuration, therefore, it is not generated by the framework.  Each instance of the Simulation Run Group would have its own id generated by the framework with each simulation group run, which is stored as a separate id from the overall Simulation Run Group id.
 */
public class SimulationRunGroup {
	static private String staticSimulationRunGroupID;
	private UUID instanceSimulationRunGroupInstanceID;
	/*
	 * Use the other constructor instead
	 */
	@SuppressWarnings("unused")
	private SimulationRunGroup() {	
	}
	
	public SimulationRunGroup(String simulationRunGroupID) {
		SimulationRunGroup.staticSimulationRunGroupID=simulationRunGroupID;
		instanceSimulationRunGroupInstanceID = UUID.randomUUID();
	}

	public static String getStaticSimulationRunGroupID() {
		return staticSimulationRunGroupID;
	}

	public UUID getInstanceSimulationRunGroupInstanceID() {
		return instanceSimulationRunGroupInstanceID;
	}



	
}
